<script lang="ts">
  import { appState } from '../stores/appState.svelte';

  let inputText = $state<string>('');
  let outputText = $state<string>('');
  let selectedTool = $state<'summarize' | 'rewrite' | 'table' | 'grammar'>('summarize');
  let selectedNotePath = $state<string>('');
  let isProcessing = $state<boolean>(false);
  let rewriteTone = $state<'professional' | 'casual' | 'academic' | 'concise'>('professional');

  // Load text from selected note
  function handleLoadNote() {
    const note = appState.notes.find(n => n.path === selectedNotePath);
    if (note) {
      inputText = note.content;
    }
  }

  // AI Mock Engine
  function processAiAction() {
    if (!inputText.trim()) {
      alert('Please enter some text or load a note first.');
      return;
    }

    isProcessing = true;
    outputText = '';

    setTimeout(() => {
      isProcessing = false;
      const text = inputText.trim();

      if (selectedTool === 'summarize') {
        // Simple sentence extractor summary mock
        const sentences = text.split(/[.!?]+/).map(s => s.trim()).filter(s => s.length > 10);
        if (sentences.length === 0) {
          outputText = `### Key Takeaways\n- Focus is on capturing thoughts clearly.\n- Add more text for a deeper summary.`;
          return;
        }
        const keyBullets = sentences.slice(0, Math.min(sentences.length, 4));
        outputText = `### Key Summary Bullet Points 📋\n\n` + 
          keyBullets.map(s => `- **Key Concept:** ${s}.`).join('\n') + 
          `\n\n*Generated by myNotes AI Summarizer*`;

      } else if (selectedTool === 'rewrite') {
        // Rewriter mock
        if (rewriteTone === 'professional') {
          outputText = `### Professional Revision 👔\n\n` + 
            `We have polished the text to establish a highly professional, business-centric vocabulary and optimized flow:\n\n` +
            text.replace(/\b(i want to|i need to)\b/gi, 'It is imperative that we')
                .replace(/\b(good|nice|cool)\b/gi, 'exceptional')
                .replace(/\b(do this|do that)\b/gi, 'execute these processes') +
            `\n\n*Generated by myNotes AI Professional Editor*`;
        } else if (rewriteTone === 'casual') {
          outputText = `### Casual Tone Revision 👋\n\n` +
            `Here is a relaxed and friendly rewrite perfect for conversational shares:\n\n` +
            `Hey! So here's the deal: ` + text.replace(/\b(therefore|consequently)\b/gi, 'so basically')
                                              .replace(/\b(implement|execute)\b/gi, 'set up')
                                              .replace(/\b(prior to)\b/gi, 'before') + 
            ` 🙌\n\n*Generated by myNotes AI Casual Editor*`;
        } else if (rewriteTone === 'academic') {
          outputText = `### Academic Analysis Revision 🎓\n\n` +
            `The narrative has been refined to utilize rigorous scholarly syntax and formal analytical structure:\n\n` +
            `A systematic review of the input parameters indicates: ` + 
            text.replace(/\b(I think)\b/gi, 'It is hypothesized')
                .replace(/\b(very|extremely)\b/gi, 'significantly')
                .replace(/\b(lots of|a lot of)\b/gi, 'a substantial multitude of') +
            `\n\n*Generated by myNotes AI Academic Editor*`;
        } else {
          // Concise
          const short = text.substring(0, Math.min(text.length, 180)) + (text.length > 180 ? '...' : '');
          outputText = `### Concise Revision ⚡\n\n` +
            `Refined and condensed version focusing purely on essential facts:\n\n` +
            `*"${short}"*\n\n*Generated by myNotes AI Concise Editor*`;
        }

      } else if (selectedTool === 'table') {
        // Table Generator
        const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
        if (lines.length === 0) {
          outputText = `| Header 1 | Header 2 |\n| --- | --- |\n| Row 1 Col 1 | Row 1 Col 2 |`;
          return;
        }

        // Try to parse CSV or space-separated lists
        let markdownTable = '';
        const parsedRows = lines.map(line => {
          if (line.includes(',')) {
            return line.split(',').map(cell => cell.trim());
          } else if (line.includes('\t')) {
            return line.split('\t').map(cell => cell.trim());
          } else {
            return line.split(/\s{2,}/).map(cell => cell.trim());
          }
        });

        const maxCols = Math.max(...parsedRows.map(r => r.length));
        if (maxCols <= 1) {
          // Fallback simple list to table
          markdownTable = `| Item Index | Content Descriptor |\n| --- | --- |\n`;
          parsedRows.forEach((r, idx) => {
            markdownTable += `| #${idx + 1} | ${r[0] || ''} |\n`;
          });
        } else {
          // Build proper header
          const headers = parsedRows[0];
          while (headers.length < maxCols) {
            headers.push(`Header ${headers.length + 1}`);
          }
          markdownTable += `| ${headers.join(' | ')} |\n`;
          markdownTable += `| ${headers.map(() => '---').join(' | ')} |\n`;
          
          // Build rows
          parsedRows.slice(1).forEach(row => {
            while (row.length < maxCols) {
              row.push('');
            }
            markdownTable += `| ${row.join(' | ')} |\n`;
          });
        }
        outputText = `### Generated Markdown Table 📊\n\n${markdownTable}\n\n*Generated by myNotes AI Table Converter*`;

      } else if (selectedTool === 'grammar') {
        // Grammar Checker mock
        let corrected = text;
        const corrections: string[] = [];

        // Simple mock substitutions for spelling & grammar check
        const rules = [
          { regex: /\bteh\b/g, replacement: 'the', msg: 'Spelling error: "teh" -> "the"' },
          { regex: /\brecieve\b/g, replacement: 'receive', msg: 'Spelling error: "recieve" -> "receive"' },
          { regex: /\bdont\b/g, replacement: "don't", msg: 'Punctuation: "dont" -> "don\'t"' },
          { regex: /\bseperate\b/g, replacement: 'separate', msg: 'Spelling error: "seperate" -> "separate"' },
          { regex: /\bi\b/g, replacement: 'I', msg: 'Capitalization: "i" -> "I"' }
        ];

        rules.forEach(rule => {
          if (rule.regex.test(corrected)) {
            corrected = corrected.replace(rule.regex, rule.replacement);
            corrections.push(rule.msg);
          }
        });

        if (corrections.length === 0) {
          outputText = `### Grammar and Style Check Clean! ✨\n\nNo glaring spelling or grammar issues were identified. Excellent writing!\n\n---\n\n${text}`;
        } else {
          outputText = `### Grammar Corrections Applied 📝\n\n` +
            `We identified and fixed ${corrections.length} style issues:\n` +
            corrections.map(c => `- *${c}*`).join('\n') +
            `\n\n#### Corrected Document Text:\n\n${corrected}`;
        }
      }
    }, 1200);
  }

  async function handleCreateNote() {
    if (!outputText) return;
    const name = prompt('Enter name for the AI note:', `${selectedTool.toUpperCase()} Output`);
    if (name !== null) {
      await appState.createNote(name);
      appState.activeNoteContent = outputText;
      await appState.saveActiveNote(true);
      appState.activeTab = 'documents';
    }
  }

  function handleCopyToClipboard() {
    if (!outputText) return;
    navigator.clipboard.writeText(outputText);
    alert('AI text copied to clipboard!');
  }
</script>

<div class="ai-container">
  <div class="header-section">
    <h1 class="title">AI Writing Assistant</h1>
    <p class="subtitle">Elevate your writing style, summarize extensive papers, audit grammar, or convert details to tables.</p>
  </div>

  <div class="ai-split-layout">
    <!-- Left Panel: Input & Tools -->
    <div class="panel input-panel">
      <!-- File Loader option -->
      <div class="note-loader-bar">
        <label for="note-select" class="md3-label-medium">Load from note:</label>
        <select id="note-select" class="note-dropdown" bind:value={selectedNotePath} onchange={handleLoadNote}>
          <option value="">-- Choose a Note --</option>
          {#each appState.notes as note}
            <option value={note.path}>{note.path}</option>
          {/each}
        </select>
      </div>

      <!-- Text Input area -->
      <textarea 
        class="input-textarea" 
        placeholder="Type, paste content, or load a note to start transforming..."
        bind:value={inputText}
      ></textarea>

      <!-- Tool selection menu -->
      <div class="tools-selector">
        <div class="tool-chips">
          <button 
            class="chip-tool" 
            class:active={selectedTool === 'summarize'}
            onclick={() => selectedTool = 'summarize'}
          >
            🔍 Summarize
          </button>
          <button 
            class="chip-tool" 
            class:active={selectedTool === 'rewrite'}
            onclick={() => selectedTool = 'rewrite'}
          >
            ✍️ Style Rewriter
          </button>
          <button 
            class="chip-tool" 
            class:active={selectedTool === 'table'}
            onclick={() => selectedTool = 'table'}
          >
            📊 CSV-to-Table
          </button>
          <button 
            class="chip-tool" 
            class:active={selectedTool === 'grammar'}
            onclick={() => selectedTool = 'grammar'}
          >
            ✅ Spell Auditor
          </button>
        </div>

        <!-- Tool specific parameters -->
        {#if selectedTool === 'rewrite'}
          <div class="tool-params">
            <span class="md3-label-medium">Rewrite Tone:</span>
            <div class="tone-options">
              {#each ['professional', 'casual', 'academic', 'concise'] as tone}
                <button 
                  class="tone-btn" 
                  class:active={rewriteTone === tone}
                  onclick={() => rewriteTone = tone as any}
                >
                  {tone}
                </button>
              {/each}
            </div>
          </div>
        {/if}
      </div>

      <button class="md3-btn process-btn" onclick={processAiAction} disabled={isProcessing}>
        {#if isProcessing}
          <div class="spinner"></div> Generating...
        {:else}
          ✨ Execute AI Action
        {/if}
      </button>
    </div>

    <!-- Right Panel: Output -->
    <div class="panel output-panel md3-card-outlined">
      <div class="output-header">
        <span class="md3-label-large">AI Output Canvas</span>
        {#if outputText}
          <div class="output-actions">
            <button class="action-icon-btn" onclick={handleCopyToClipboard} title="Copy to clipboard">📋</button>
            <button class="action-icon-btn" onclick={handleCreateNote} title="Save as note">💾</button>
          </div>
        {/if}
      </div>

      {#if isProcessing}
        <div class="output-loading">
          <div class="pulse-loader"></div>
          <p>Processing text parameters and crafting layout...</p>
        </div>
      {:else if outputText}
        <div class="output-content">
          <pre>{outputText}</pre>
        </div>
      {:else}
        <div class="output-empty">
          <div class="magic-icon">🔮</div>
          <p>AI results will appear here after executing an action on the left.</p>
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  .ai-container {
    padding: 32px;
    max-width: 1200px;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    height: 100%;
    animation: fadeIn 0.3s ease-out;
  }

  @keyframes fadeIn {
    from { opacity: 0; transform: translateY(10px); }
    to { opacity: 1; transform: translateY(0); }
  }

  .header-section {
    margin-bottom: 24px;
    flex-shrink: 0;
  }

  .title {
    font-family: var(--font-sans);
    font-size: 32px;
    font-weight: 800;
    margin-bottom: 6px;
    letter-spacing: -0.5px;
  }

  .subtitle {
    color: var(--text-secondary);
    font-size: 15px;
  }

  .ai-split-layout {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 24px;
    flex-grow: 1;
    min-height: 0; /* Important for scroll container */
    margin-bottom: 24px;
  }

  .panel {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-height: 0;
  }

  /* Note selector dropdown */
  .note-loader-bar {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-bottom: 12px;
    flex-shrink: 0;
  }

  .note-dropdown {
    flex-grow: 1;
    background-color: var(--bg-surface-container);
    border: 1px solid var(--border-color);
    border-radius: var(--radius-s);
    padding: 8px 12px;
    color: var(--text-primary);
  }

  /* Input area */
  .input-textarea {
    flex-grow: 1;
    background-color: var(--bg-surface);
    border: 1px solid var(--border-color);
    border-radius: var(--radius-m);
    padding: 16px;
    color: var(--text-primary);
    resize: none;
    font-family: var(--font-sans);
    font-size: 14px;
    line-height: 1.6;
    margin-bottom: 16px;
  }

  .input-textarea:focus {
    border-color: var(--primary);
  }

  /* Tools options */
  .tools-selector {
    background-color: var(--bg-surface-container);
    border-radius: var(--radius-m);
    padding: 16px;
    margin-bottom: 16px;
    flex-shrink: 0;
  }

  .tool-chips {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
  }

  .chip-tool {
    padding: 8px 16px;
    border-radius: var(--radius-s);
    background-color: var(--bg-surface);
    border: 1px solid var(--border-color);
    color: var(--text-secondary);
    font-size: 13px;
    font-weight: 600;
    transition: var(--transition-fast);
  }

  .chip-tool:hover {
    border-color: var(--text-tertiary);
  }

  .chip-tool.active {
    background-color: var(--primary);
    color: var(--on-primary);
    border-color: transparent;
  }

  .tool-params {
    margin-top: 14px;
    display: flex;
    flex-direction: column;
    gap: 8px;
    animation: slideDown 0.2s ease-out;
  }

  @keyframes slideDown {
    from { opacity: 0; transform: translateY(-5px); }
    to { opacity: 1; transform: translateY(0); }
  }

  .tone-options {
    display: flex;
    gap: 6px;
  }

  .tone-btn {
    padding: 4px 10px;
    font-size: 12px;
    font-weight: 500;
    border: 1px solid var(--border-color);
    border-radius: var(--radius-xs);
    background-color: var(--bg-surface);
    text-transform: capitalize;
  }

  .tone-btn.active {
    background-color: var(--secondary-container);
    color: var(--on-secondary-container);
    border-color: transparent;
  }

  .process-btn {
    width: 100%;
    height: 48px;
    flex-shrink: 0;
  }

  /* Output panel layout */
  .output-panel {
    background-color: var(--bg-surface);
    border-radius: var(--radius-l);
    padding: 0; /* Keep header separate */
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  .output-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 16px 20px;
    border-bottom: 1px solid var(--border-color);
    background-color: var(--bg-surface-container);
    flex-shrink: 0;
  }

  .output-actions {
    display: flex;
    gap: 8px;
  }

  .action-icon-btn {
    width: 32px;
    height: 32px;
    border-radius: var(--radius-circle);
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: var(--bg-surface);
    border: 1px solid var(--border-color);
    cursor: pointer;
    font-size: 14px;
  }

  .action-icon-btn:hover {
    background-color: var(--bg-surface-variant);
  }

  .output-content {
    padding: 20px;
    overflow-y: auto;
    flex-grow: 1;
  }

  .output-content pre {
    white-space: pre-wrap;
    word-break: break-word;
    font-family: var(--font-sans);
    font-size: 14px;
    line-height: 1.6;
    color: var(--text-primary);
  }

  .output-loading {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    flex-grow: 1;
    color: var(--text-secondary);
    gap: 16px;
  }

  .pulse-loader {
    width: 40px;
    height: 40px;
    border: 4px solid var(--border-color);
    border-top-color: var(--primary);
    border-radius: var(--radius-circle);
    animation: spin 1s infinite linear;
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .output-empty {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    flex-grow: 1;
    color: var(--text-tertiary);
    text-align: center;
    padding: 40px;
  }

  .magic-icon {
    font-size: 48px;
    margin-bottom: 12px;
    opacity: 0.7;
  }

  .spinner {
    width: 16px;
    height: 16px;
    border: 2px solid var(--on-primary);
    border-top-color: transparent;
    border-radius: var(--radius-circle);
    animation: spin 0.8s infinite linear;
    display: inline-block;
  }

  @media (max-width: 768px) {
    .ai-container {
      padding: 16px;
    }
    .title {
      font-size: 26px;
    }
    .ai-split-layout {
      grid-template-columns: 1fr;
      overflow-y: visible;
    }
    .input-textarea {
      min-height: 250px;
    }
    .output-panel {
      min-height: 300px;
    }
  }
</style>
